### PR TITLE
New entries by erickpatrick

### PR DESCRIPTION
**Pull request by erickpatrick**
This pull request has been automatically generated by Github.js

### CODE REVIEW

**Comment by idoco** [comment]
Thanks for sharing.
I noticed that you didn't add your contact details, I will merge this pull request and if you want to add something to it you can manually edit the entry in a new pull request in the future.
(Maybe add a link to http://www.erickpatrick.net/ ?)

That makes me think that I should add a contact details field to the submission form.

**Comment by erickpatrick** [comment]
Hi Ido Cohen,

You could also use the e-mail field form Github itself as the contact
e-mail, like other systems do. You already ask permission for personal
details, using the e-mail shouldn't be that hard.

But, sure, you could add a contact details field to the form =)

Cheers,

**Comment by idoco** [comment]
Yes! That is a good idea. 
I wasn't sure if it is safe to store raw emails in a public json file on GitHub. Maybe I can just add a link to the GitHub user page which already contains their contact details?

**Comment by erickpatrick** [comment]
Hi again!

GitHub user page would be a nice solution too.

But, regarding saving emails in plain JSON: if someone puts it manually it
would be
saved anyway in a plain JSON, right? The only difference would be that they
would do that proactively.

On the other side, if you do that "automagically" and you're actively
asking permissions
to get our e-mails and we say yes, we're also allowing you to display it,
so to say.

Anyway, there's a thin line, I know, but you could use directly (the
e-mail, I mean) or
create a link to the user's GitHub page =)

Cheers,

**Comment by idoco** [comment]
Yeah, I agree, I meant that doing it automatically sounds problematic so adding just a GitHub account might be better. 
The change is small so I will implement this and see how works out. 
Thanks for the feedback!

**Comment by erickpatrick** [comment]
Sure, no problem! Happy to help you =)

Nice coding o/

Cheers,

**Pull request merged**
